import { Brand } from "@/constants/theme";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Brand.bg,
  },
  backgroundArt: {
    ...StyleSheet.absoluteFillObject,
    overflow: "hidden",
    backgroundColor: Brand.welcomeBg,
  },
  backdropPanel: {
    position: "absolute",
    top: -120,
    left: -150,
    width: 430,
    height: 980,
    borderRadius: 80,
    backgroundColor: Brand.welcomePanel,
    opacity: 0.42,
    transform: [{ rotate: "-24deg" }],
  },
  backdropPanelSoft: {
    position: "absolute",
    top: -70,
    right: -210,
    width: 380,
    height: 1040,
    borderRadius: 90,
    backgroundColor: Brand.welcomePanelDark,
    opacity: 0.72,
    transform: [{ rotate: "21deg" }],
  },
  backdropVignette: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: Brand.welcomeOverlay,
  },
  content: {
    flexGrow: 1,
    paddingHorizontal: 48,
    paddingTop: 56,
    paddingBottom: 24,
  },
  logoRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    marginBottom: 72,
  },
  logoMark: {
    width: 54,
    height: 54,
  },
  logoText: {
    color: Brand.welcomeLogo,
    fontSize: 22,
    fontWeight: "900",
    fontStyle: "italic",
    letterSpacing: 0,
  },
  heroSubtitle: {
    color: Brand.welcomeSubtitle,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "400",
    letterSpacing: 8,
    textTransform: "uppercase",
    marginBottom: 16,
  },
  heroTitle: {
    color: Brand.welcomeTitle,
    fontSize: 48,
    lineHeight: 51,
    fontWeight: "900",
    letterSpacing: 0,
    textTransform: "uppercase",
  },
  heroTitleGreen: {
    color: Brand.green,
  },
  tagline: {
    color: Brand.white,
    fontSize: 16,
    lineHeight: 24,
    marginTop: 56,
    maxWidth: 320,
  },
  bottom: {
    marginTop: "auto",
    gap: 14,
  },
  primaryButton: {
    minHeight: 56,
    backgroundColor: Brand.buttonPrimaryBg,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  primaryButtonText: {
    color: Brand.buttonPrimaryText,
    fontSize: 18,
    fontWeight: "700",
    letterSpacing: 0,
  },
  appleButtonWrap: {
    minHeight: 56,
  },
  appleButton: {
    height: 56,
  },
  secondaryButton: {
    minHeight: 56,
    borderRadius: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Brand.welcomeGoogleBg,
  },
  secondaryButtonText: {
    color: Brand.white,
    fontSize: 16,
    fontWeight: "700",
    letterSpacing: 0,
  },
  createRow: {
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
    marginTop: 10,
  },
  createText: {
    color: Brand.white,
    fontSize: 12,
    lineHeight: 16,
    flexShrink: 1,
  },
  createButton: {
    minHeight: 44,
    paddingHorizontal: 0,
    alignItems: "center",
    justifyContent: "center",
  },
  createButtonText: {
    color: Brand.green,
    fontSize: 14,
    fontWeight: "700",
  },
});
